Simple led example
relu91/webthing-arduino pull request #11
Opened 2021-08-19 00:48 UTC by Citrullin

Add a simple LED on/off example.

2021-08-23 15:43 UTC, relu91 commented on examples/LED/LED.ino
> +#include <Thing.h>
logically `Thing.h` is not a system library, why did you change `"` to `<`?

2021-08-23 15:53 UTC, relu91 requested changes
A minor issue below.

2021-08-23 15:53 UTC, relu91 commented on examples/LED/LED.ino
> +  if (state) {
isn't this code redundant? the pin will be written soon after the action handler execution in the loop function.

2021-08-25 21:39 UTC, Citrullin commented on examples/LED/LED.ino
> +#include <Thing.h>
That's true. I don't know. Copy, paste, I think? ^^

2021-08-25 21:58 UTC, Citrullin commented on examples/LED/LED.ino
> +  if (state) {
true. I didn't really pay much attention to it.

2021-08-25 23:35 UTC, Citrullin commented
@relu91 Updated it.

2021-08-31 09:15 UTC, relu91 approved these changes

2021-08-31 09:15 UTC, merged